meta_product_name: "Follow Me"
meta_title: "Follow Me - Find a tour. Explore with a local"
meta_description: "Want to explore a city (minus the same old tourist attractions)? Follow me can help you find what you are looking for based on your interests...with a local!"
meta_image: "cover.png"
twitter_account: "@lewagonberlin"
